name: AI POS SaaS E2E Local
values:
  - key: baseUrl
    value: 'http://localhost:8080'
    enabled: true
  - key: keycloakBaseUrl
    value: 'http://localhost:8081'
    enabled: true
  - key: keycloakAdminBaseUrl
    value: 'http://localhost:8081'
    enabled: true
  - key: realm
    value: ai-pos
    enabled: true
  - key: clientId
    value: pos-client
    enabled: true
  - key: tenantAdminEmail
    value: admin@malar.com
    enabled: true
  - key: tenantAdminPassword
    value: Password1
    enabled: true
  - key: tenantName
    value: malar.com
    enabled: true
  - key: cashierEmail
    value: malar@malar.com
    enabled: true
  - key: cashierPassword
    value: Password1
    enabled: true
  - key: tenantAdminToken
    value: ''
    enabled: true
  - key: cashierToken
    value: ''
    enabled: true
  - key: tenantId
    value: ''
    enabled: true
  - key: tenantAdminUserId
    value: ''
    enabled: true
  - key: tenantAdminUsername
    value: ''
    enabled: true
  - key: cashierUserId
    value: ''
    enabled: true
  - key: cashierUsername
    value: ''
    enabled: true
  - key: product1Id
    value: ''
    enabled: true
  - key: product2Id
    value: ''
    enabled: true
  - key: orderId
    value: ''
    enabled: true
color: 240
